import streamlit as st

Questions = {
  "Biology": [
    "Are gender traits completely a result of societal expectations?",
    "Are there any parts of the human body that get oxygen directly from the air and not from the blood?",
    "Are there nuclear reactions going on in our bodies?",
    "Can humans ever directly see a photon?",
    "Can I turn my cat into a diamond?",
    "Do blind people dream in visual images?",
    "Do Kirlian photographs show the soul of an organism?",
    "Do koalas eat honey like other bears?",
    "Do poppy seeds contain narcotics?",
    "Does the human body contain minerals?",
    "How can the heart be strong enough to pump blood up your legs against gravity?",
    "How can we differentiate so many different foods if we can only taste four flavors on our tongue: sweet, bitter, sour, and salty?",
    "How can we unlock the 90% of our brain that we never use?",
    "How did doctors create my belly button?",
    "How did evolution ever lead ostriches to hide their head in the sand when an enemy approaches?",
    "How do 5G cell phone signals harm humans?",
    "How do I turn on more parts of my brain and get smarter?",
    "How do nerves control every organ and function in the body?",
    "How do trees give earth all its oxygen?",
    "How does the outer layer of skin cells on my finger detect when I am touching an object?",
    "How long before genetic sequencing is able to tell us exactly how our children will look and act?",
    "How long does it take our eyes to fully adapt to darkness?",
    "How much water can a camel store in its hump?",
    "How strong does a non-toxic odor have to be before it damages your sense of smell?",
    "Is human blood ever any color other than red?",
    "Is ionizing radiation always harmful?",
    "Is it completely random whether a baby is a boy or a girl?",
    "What are the five senses of the human body?",
    "What chemicals can make human tissue regenerate in seconds?",
    "What is it about a full moon that makes people do crazy things and commit crimes?",
    "What is it about red that makes bulls so angry?",
    "When did humans stop evolving?",
    "When do birds use their teeth?",
    "Where in my body is the original cell from which I was formed?",
    "Why are bats blind?",
    "Why are human brains the biggest?",
    "Why are red, yellow, and blue the primary colors in painting but computer screens use red, green, and blue?",
    "Why are veins blue?",
    "Why can only certain parts of the tongue taste sweet flavors? Is there an evolutionary benefit to this?",
    "Why can you boil a frog without it jumping out to safety if you raise the temperature slowly?",
    "Why can't color blind people see any colors?",
    "Why did evolution create a chicken that lays so many unfertilized eggs when that is so wasteful?",
    "Why do camera flashes make your eyes turn red?",
    "Why do humans have an appendix even though it is unnecessary?",
    "Why do my fingers absorb water and become wrinkled?",
    "Why does chewing gum take seven years to digest?",
    "Why does every cell in our body contain DNA?",
    "Why does evolution always lead to more advanced species?",
    "Why don't dogs sweat?",
    "Why don't I burst cells in my rear when I sit down?",
    "Why don't our eyeballs fill up with water when we swim?",
    "Why don't trees freeze and burst in the winter like cold pipes?",
    "Why have humans evolved to be taller over the last three hundred years?",
    "Why will a mother bird abandon its chick if touched by a human?"
  ],
  
  "Chemistry": [
    "Are two atoms of the same element identical?",
    "Can water stay liquid below zero degrees Celsius?",
    "Can you light diamond on fire?",
    "How bad of an alcoholic do you have to be to have your brain affected?",
    "How can glass be a liquid if it's so hard?",
    "How do I know if something is an acid so I can avoid eating it?",
    "How do plants get their nitrogen from the air?",
    "How does dissolving a salt molecule in water make its atoms ionize?",
    "How does plasma make a campfire flame orange?",
    "How does tomato juice make skunk smell go away?",
    "What is it about the ocean that makes it look blue when it reflects the sky?",
    "What is the difference between a chemical process and a physical process in chemistry?",
    "What kind of crystal are crystal drinking glasses made out of?",
    "What made the hole in the ozone go away?",
    "What makes a 'fluorescent' highlighter marker so bright?",
    "When does the breaking of chemical bonds release energy?",
    "When hang-drying clothes, which is faster, indoors or outdoors?",
    "Which sunscreens are chemical-free?",
    "Why are crystals rare?",
    "Why are there so many different kinds of forces in chemistry?",
    "Why do atoms always contain the same number of electrons and protons?",
    "Why doesn't the planet Uranus explode if it contains so much hydrogen and methane?",
    "Why don't metals burn?",
    "Why don't objects fuse to my finger when I touch them?",
    "Why is ice slippery?",
    "Why is lead used in pencils even though lead is poisonous?",
    "Why is mass conserved in chemical reactions?",
    "Why is plastic not used in home construction?",
    "Why is propane stored in household tanks but natural gas is not?",
  ],

  "Earth Science": [
    "Can it rain fish?",
    "Can wind travel faster than the speed of sound?",
    "Clouds are just water vapor, so why do they move?",
    "Do I weigh less on the equator than at the North Pole?",
    "Does the back of a rainbow look the same as its front side?",
    "Does wasting household water remove it from the water cycle?",
    "How can there be clouds in winter when it is too cold for water to stay a vapor?",
    "How do geologists use carbon dating to find the age of rocks?",
    "How do icebergs lose their salt?",
    "How do wells get their water from underground rivers?",
    "How does a cloud fill up with water?",
    "How does diffraction make a tree's shadow blurry?",
    "How does trash in the ocean disappear?",
    "How does water dowsing work?",
    "How does wind create all the ocean currents?",
    "If I jump, will the entire earth move a little bit?",
    "If I were able to dig a hole from the U.S. through the center of the earth, what part of China would I end up in?",
    "Is a quadruple rainbow possible?",
    "What causes the water going down a drain to swirl clockwise in the northern hemisphere and counter-clockwise in the southern hemisphere?",
    "What keeps the continents floating on a sea of molten rock?",
    "What makes rain drops tear shaped?",
    "What makes the Sahara the largest desert in the world?",
    "What makes the soil in tropical rainforests so rich?",
    "What would happen if you fell into a hole that went through the center of the earth?",
    "Where do ocean tides get their energy from?",
    "Where does the atmosphere end? Where is the edge of space?",
    "Where is the safest place to go when a tornado hits?",
    "Why can't lightning strike the same place twice?",
    "Why did so many people believe the world is flat when it is obviously a sphere?",
    "Why do car tires protect you from lightning strikes?",
    "Why does a magnetic compass point to the Geographic North Pole?",
    "Why does ice form on the top of a lake?",
    "Why does the air only contain water vapor and not other kinds of vapors?",
    "Why does the coldest time of the year align with the darkest time of the year?",
    "Why doesn't the outside world appear blue even though so much light comes from the blue sky?",
    "Why don't the gases in the atmosphere separate out according to mass?",
    "Why don't the oceans freeze?",
    "Why is the sky blue?",
    "Why is the sky not blue as seen from space?",
    "Why is the sun cold in the winter?"
  ],

  "Health": [
    "Is mental illness really an illness? (January 8, 2024)",
    "How can I tell if I have depression or just normal sadness?",
    "Are any pills perfectly safe?",
    "Can a man's testosterone be boosted naturally?",
    "Did cancer exist before man-made chemicals were around to create it?",
    "Do humans give off radiation?",
    "Does licorice cause high blood pressure?",
    "How can I tell if I have depression or just normal sadness?",
    "How can Lyme disease last for years?",
    "How do antibiotics kill viruses?",
    "How do baby walkers teach a baby to walk sooner?",
    "How do carrots help you see in the dark?",
    "How do magnets heal?",
    "How do vaccines cause autism?",
    "How do your intestines detox your body?",
    "How does dust get in a house when the doors and windows are always closed?",
    "How does ice cream in your stomach cause a headache?",
    "How does not washing your hands make you a healthier person?",
    "How long can you wait after dropping food on the ground to eat it without having germs attached? Some say it's a five-second rule, others say ten.",
    "How long do you have to exercise for it to count?",
    "How much extra radiation am I exposed to if I stick my hand in the microwave right after it turns off?",
    "How often should hydrogen peroxide be used to treat wounds?",
    "I know anything from a plant is safe to eat, but anything from a lab can be dangerous. How can I tell if something came from a plant or a lab?",
    "Is fruit juice healthier than whole fruit?",
    "Is mental illness really an illness?",
    "What is the debate over vaccines?",
    "What is the most harmful pseudo-science?",
    "What part of the brain is hurt when you get headaches?",
    "What should I do if I can't swallow pills?",
    "When someone's heart skips a beat, what is wrong with his heart?",
    "Why are cancer mortality rates rising?",
    "Why do cold temperatures give you a cold?",
    "Why do heart attacks always cause chest pain?",
    "Why do humans crave sugary foods? Shouldn't evolution lead us to crave healthy foods?",
    "Why do women get more tooth problems during pregnancy?",
    "Why does chocolate cause acne?",
    "Why does mainstream medicine only treat patients with drugs?",
    "Why don't dark-skinned people get sunburns?",
    "Why isn't there just one cure for cancer?"
  ],

  "Physics": [
    "What are some fake-science headlines that reappear regularly? (May 15, 2024)",
    "How can glass produce glare without reflecting light? (April 19, 2024)",
    "Why is the speed of light a random finite number? (February 7, 2024)",
    "Is there a difference between thermal radiation and infrared radiation? (December 13, 2023)",
    "When does light travel in a straight line? (November 22, 2023)",
    "Are there any massless particles? (October 23, 2023)",
    "Why don't the gases in the atmosphere separate out according to mass? (September 19, 2023)",
    "Why does a person with only one working eye have zero depth perception? (July 28, 2023)",
    "How do 5G cell phone signals harm humans? (August 18, 2022)",
    "How can radioactive decay just happen with nothing triggering it? (August 11, 2022)",
    "Why is gravity not a real force? (August 5, 2022)",
    "Where does the atmosphere end? Where is the edge of space? (June 6, 2024)",
    "What is the difference between a law, a principle, a theory, and a hypothesis in science? (July 24, 2024)",
    "Why does the air only contain water vapor and not other kinds of vapors? (June 11, 2022)",
    "Are there different types of black holes?",
    "Is a black hole a 2D or a 3D object?",
    "Where do ocean tides get their energy from?",
    "What is the most stable nucleus?",
    "Does everything get smashed to bits when two galaxies collide?",
    "Are there any massless particles?",
    "As light from a star spreads out and weakens, do gaps form between the photons?",
    "Can a fire have a shadow?",
    "Can air make shadows?",
    "Can gold be created from other elements?",
    "Can light bend around corners?",
    "Can momentum be hidden to human eyes like how kinetic energy can be hidden as heat?",
    "Can one bit of light bounce off another bit of light?",
    "Can radio antennas emit visible light?",
    "Can sound waves generate heat?",
    "Can the decay half-life of a radioactive material be changed?",
    "Can you go fast enough to get enough mass to become a black hole?",
    "Can you make a shock wave of light by breaking the light barrier just like supersonic airplanes break the sound barrier?",
    "Can you make a sunset in a cup of milk?",
    "Could electronic devices charge themselves without being plugged into an electricity source?",
    "Could scientists perfectly simulate the entire universe in a computer, down to the last atom?",
    "Do atoms ever actually touch each other?",
    "Do flames contain plasma?",
    "Does a source of electricity ever run out of electrons?",
    "Does an atom have a color?",
    "Does an electron in an atom move at all?",
    "Does the negative mass of antimatter mean that it's gravitationally repelled from stars?",
    "Does time go faster at the top of a building compared to the bottom?",
    "How bad would a person's injuries be if an elevator's cables snapped at the 100th floor so that the elevator fell to the bottom?",
    "How can a clear object be transparent and visible at the same time?",
    "How can a material at a certain temperature have all of its molecules at the same energy?",
    "How can an electron leap between atomic levels without passing through all the space in between?",
    "How can glass produce glare without reflecting light?",
    "How can it be so hard to drag rubber across smooth glass if friction is caused by surface roughness?",
    "How can radioactive decay just happen with nothing triggering it?",
    "How can we travel to the past?",
    "How did Archimedes use mirrors to burn up invaders' ships?",
    "How do airplanes fly upside down if it's the shape of the wings that make them fly?",
    "How do free energy machines work?",
    "How do levers create energy if the conservation of energy does not allow energy to be created?",
    "How do projectors project the color black?",
    "How do scientists cool objects to absolute zero?",
    "How do tractor beams work?",
    "How do you focus regular light to make it a laser beam?",
    "How do you make a one-photon-thick beam of light?",
    "How does a microwave oven heat up food even though it emits no thermal radiation?",
    "How does a penny left on the track derail a train?",
    "How does a photon accelerate to light speed so quickly?",
    "How does quantum theory allow a rock to turn suddenly into a duck?",
    "How does sound going slower in water make it hard to talk to someone underwater?",
    "How high does a building have to be for a penny dropped from the top to kill a person on the ground?",
    "How is a magnetic field just an electric field with relativity applied?",
    "How long can you use a cell phone before getting a brain tumor?",
    "If I hammered and flattened a penny enough, could I cover the entire earth with it?",
    "If I'm on an elevator that breaks loose and plummets down the shaft, can I avoid harm by jumping at the last second?",
    "Is it possible to create magnetic waves?",
    "Is light a particle or a wave?",
    "Is metal a good heat shield?",
    "Is the reason that nothing can go faster than light because we have not tried hard enough?",
    "Is there a difference between thermal radiation and infrared radiation?",
    "Is there any difference between antimatter, dark matter, dark energy, and degenerate matter?",
    "Light has no mass so it also has no energy according to Einstein, but how can sunlight warm the earth without energy?",
    "Since gravity is unlimited, can we use it as an infinite energy source?",
    "What are some other ways to save energy in a car besides turning off the air conditioner and rolling down the windows?",
    "What did Schrodinger's Cat experiment prove?",
    "What is the most stable nucleus?",
    "What is the shape of an electron?",
    "What is the speed of dark?",
    "What is the speed of electricity?",
    "What is the speed of gravity?",
    "What is the strongest magnetic field possible? Is there a limit?",
    "What keeps a bicycle balanced?",
    "What makes heat rise?",
    "What makes radioactive atoms get old so quickly and decay?",
    "What makes the light waves in laser light parallel?",
    "What psychological effect makes notes on a piano that are an octave apart sound the same?",
    "What stops a piece of paper from being folded more than seven times?",
    "What would happen if you drove your car close to the speed of light and turned on the headlights?",
    "When does a light beam have only a single frequency?",
    "When does light travel in a straight line?",
    "When I bump one end of a long metal bar, the other end instantaneously moves. Can I use this to send messages faster than light?",
    "When I sit by a campfire, how does its hot air heat me?",
    "When I step out of the shower, what makes the tile floor so much colder than the bathroom mat?",
    "Why are all metals magnetic?",
    "Why are sound waves invisible?",
    "Why are the microwaves in a microwave oven tuned to water?",
    "Why are there only six fundamental colors: red, orange, yellow, green, blue, and violet?",
    "Why can't flat lenses focus light?",
    "Why do diamonds last forever?",
    "Why do mirrors flip left to right and not up to down?",
    "Why do quantum effects only happen on the atomic scale?",
    "Why does a person with only one working eye have zero depth perception?",
    "Why does a rainbow contain a pure spread of spectral colors?",
    "Why does a rainbow exist only in a narrow band?",
    "Why does air friction affect a car's gas mileage?",
    "Why does lightning push electricity through air, but common batteries do not?",
    "Why does my room get dark when I turn the lights off even if my window is shut?",
    "Why does water make a shirt darker?",
    "Why doesn't light carry momentum?",
    "Why doesn't my laptop emit radiation?",
    "Why don't atoms collapse if they are mostly empty space?",
    "Why don't electrons in the atom enter the nucleus?",
    "Why don't I feel the miles of air above me that are crushing me down?",
    "Why don't scientists use fractal concepts more considering that fractals are everywhere?",
    "Why is a 12-volt household battery harmless, but the shock from a 12-volt car battery will kill you?",
    "Why is gravity not a real force?",
    "Why is light pure energy?",
    "Why is physics scale invariant?",
    "Why is the centrifugal force talked about so much if it's not real?",
    "Why is the lowest temperature called absolute zero if it's relative to the frame of reference?",
    "Why is the speed of light a random finite number?",
    "Why is time frozen from light's perspective?",
    "Why was color invented by humans?",
    "Why were electrons chosen to be negatively charged? Wouldn't it make more sense to call electrons positively charged because when they move they make electricity?",
    "Why will a delivery truck filled with birds sitting on its floor be heavier than a truck with the same birds flying around inside?"
  ],

  "Society": [
    "Do scientists have a hard time understanding art?",
    "How can I find accurate science information on the internet?",
    "How can I tell whether my friend's scientific explanation is accurate?",
    "How can I win the lottery?",
    "How can science solve all of our problems?",
    "How did Albert Einstein flunk math and still end up so smart?",
    "How many years do we have until the earth becomes so over-populated that people won't be allowed to have children?",
    "How much money do I save by recharging my cell phone at work?",
    "I watched a science documentary and then came up with my own theory. Where can I get it published?",
    "Is there a difference between mainstream science and alternative science?",
    "What are some fake-science headlines that reappear regularly?",
    "What is the difference between a law, a principle, a theory, and a hypothesis in science?",
    "What is the most harmful drug to society?",
    "What makes guns so dangerous?",
    "What makes x so special that you see it all the time in equations?",
    "What part of China do fortune cookies come from?",
    "What part of France invented French toast?",
    "What part of Germany does German chocolate cake come from?",
    "When will the technological singularity occur?",
    "When will the written word become obsolete?",
    "Who invented the scientific method?",
    "Why are refried beans cooked twice?",
    "Why are scientists atheists?",
    "Why are truck drivers rude?",
    "Why do most international phone calls and data links go through satellites?",
    "Why do people believe in conspiracy theories?",
    "Why do scientists write so well?",
    "Why is speculation forbidden in science?"
  ],

  "Space": [
    "Are there different types of black holes?",
    "Can a star turn into a planet?",
    "Can gravity form waves?",
    "Does every black hole contain a singularity?",
    "Does everything get smashed to bits when two galaxies collide?",
    "Does sound travel faster in space?",
    "Does the influence of gravity extend out forever?",
    "Galaxies look stationary, so why do scientists say that they rotate?",
    "Have aliens ever visited earth?",
    "Have astronomers ever observed a violet shift like they have blue shifts and red shifts?",
    "How bright is a laser beam when viewed from the side?",
    "How can astronomers know things for certain since they only look at space from one vantage point?",
    "How can there be anything left in the universe? Don't black holes suck everything in?",
    "How can you cancel out the jolt of a quick start?",
    "How can you tell a black hole made out of antimatter from a black hole made out of matter?",
    "How do space probes make it past the asteroid belt without crashing into asteroids?",
    "How do space ships fly faster than light?",
    "How do space ships make artificial gravity?",
    "How do stars move when viewed from a speeding space ship?",
    "How does a black hole give off light?",
    "How does a supernova completely destroy a star?",
    "How does astrology work?",
    "How does looking at distant galaxies allow us to look back in time?",
    "How does the expansion of the universe make outer space a vacuum?",
    "How large would a bucket of water have to be to put out the sun?",
    "How long before the expansion of the universe causes our earth to drift away from the sun?",
    "How long can a human in outer space last without a spacesuit before exploding?",
    "How often does the sun's magnetic field flip?",
    "I know that the gravity of the moon causes ocean tides on earth. How does centrifugal force cause the far-side bulge?",
    "Is a black hole a 2D or a 3D object?",
    "Is Pluto a planet?",
    "Since a star's light takes so long to reach us, how do we know that the star is still there?",
    "Since one satellite can see half of the earth, why do we need more than two satellites in a given network?",
    "What could a space ship do if it stopped because it ran out of fuel?",
    "What is the color of the sun?",
    "What is the overall electric charge of the universe?",
    "What is the range of weapons if used in space?",
    "What keeps space empty?",
    "What keeps the North Star stuck at exactly North?",
    "What keeps the sun spinning?",
    "What kind of space ships can make banking turns?",
    "What makes meteorites so hot that you can't touch them?",
    "What makes space so cold?",
    "What makes the Great Wall of China the only man-made object visible from space?",
    "What would space ships actually look like in space?",
    "When do the planets in our solar system all line up?",
    "Where is the center of the universe?",
    "Where is the edge of the universe?",
    "Which space movie has the most accurate physics?",
    "Why are all the stars fixed in space?",
    "Why are stars not blurred even though the earth is moving?",
    "Why did NASA spend millions developing a pen that would work in space when a pencil is just as good?",
    "Why did people believe the earth is the center of the solar system when it's obvious the sun is?",
    "Why do the spikes that shoot out of stars form perfect crosses?",
    "Why does everything in our galaxy orbit the supermassive black hole at the center?",
    "Why does the moon get bigger when it's closer to the horizon?",
    "Why does the moon's gravity cause tides on earth but the sun's gravity doesn't?",
    "Why does the sun not run out of oxygen as it burns?",
    "Why doesn't the earth fall down?",
    "Why don't galaxies have a natural magnetic field like the earth does?",
    "Why is gravity the strongest force?",
    "Why is the moon so bright?",
    "Why is there no gravity in space?",
    "Why is there no up and down in space?",
    "Will the night sky eventually end up completely black because the universe is expanding?",
    "Would a guitar sound the same on a space station?"
  ]
}

# Sidebar menu for selecting the subject
st.sidebar.title("Select Subject")
subject = st.sidebar.selectbox("Choose a subject", list(Questions.keys()))

# Display questions for the selected subject
questions = Questions[subject]

for i, question in enumerate(questions):
    st.write(f"{i+1}. {question}")
    
    # Create an "Ask LLM" button for each question
    if st.button(f"Ask LLM", key=i):
        # Simulate querying the LLM and display a dummy response
        # Replace this section with actual LLM integration, such as with Langchain, OpenAI, or Ollama
        st.write(f"LLM's answer to: {question}")
        # Here, you can add a call to your LLM model to get the actual answer.

    st.divider()
